import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:golden_matrix/src/core/join_path.dart';
import 'package:golden_matrix/src/core/warn.dart';

/// Well-known system fonts that should not be namespaced with a package prefix.
const _overridableFonts = [
  'Roboto',
  '.SF UI Display',
  '.SF UI Text',
  '.SF Pro Text',
  '.SF Pro Display',
];

/// Loads fonts declared in the app's pubspec.yaml and its dependencies.
///
/// Two sources are consulted, in order:
///
/// 1. **`FontManifest.json`** — the manifest generated by the Flutter
///    tool, listing every font family bundled by the app and its
///    dependencies. Each eligible family in the manifest is registered
///    with Flutter's [FontLoader].
/// 2. **Roboto + MaterialIcons from the Flutter SDK cache** — if either
///    is not already present in the manifest, this function locates the
///    SDK (via `FLUTTER_ROOT`, or by finding the `flutter` launcher on `PATH`
///    and resolving it) and loads
///    `bin/cache/artifacts/material_fonts/Roboto-Regular.ttf` /
///    `MaterialIcons-Regular.otf`. These fallbacks let Material widgets
///    render real glyphs in tests instead of the default Ahem placeholder
///    text and empty-box icons.
///
/// Call this in `flutter_test_config.dart` before running golden tests:
///
/// ```dart
/// // test/flutter_test_config.dart
/// Future<void> testExecutable(FutureOr<void> Function() testMain) async {
///   await loadAppFonts();
///   return testMain();
/// }
/// ```
///
/// ## Selective loading
///
/// Pass [textFonts] and/or [iconFonts] to load only a subset:
///
/// ```dart
/// // Layout-deterministic tests — Ahem text geometry + real icons.
/// // Useful when text metrics drift across macOS/Linux CI but icons
/// // must still be visually recognizable for review.
/// await loadAppFonts(textFonts: false);
///
/// // Real text, no icons — niche, but supported.
/// await loadAppFonts(iconFonts: false);
///
/// // Pure Ahem — equivalent to never calling loadAppFonts().
/// await loadAppFonts(textFonts: false, iconFonts: false);
/// ```
///
/// Icon families are detected by the [isIconFamily] heuristic
/// (case-insensitive substring match on `'icons'` or `'symbols'`).
/// This catches `MaterialIcons`, `CupertinoIcons`, `FontAwesomeIcons`,
/// `MaterialSymbolsRounded`, etc. Icon fonts that don't follow this
/// naming convention (e.g. `Phosphor`) will be treated as text fonts
/// — file an issue if this matters for your project.
Future<void> loadAppFonts({bool textFonts = true, bool iconFonts = true}) async {
  TestWidgetsFlutterBinding.ensureInitialized();

  // Load fonts from FontManifest.json (app + dependency fonts)
  // Decoded as `Object?`, not cast to `Iterable`: an unexpected manifest shape
  // is reported by planFontRegistrations rather than thrown out of
  // `flutter_test_config.dart`.
  final fontManifest = await rootBundle.loadStructuredData<Object?>(
    'FontManifest.json',
    (string) async => json.decode(string) as Object?,
  );

  // Decide what to register (which families, under which names, from which
  // assets) as pure logic, then perform the FontLoader mechanics here.
  final registrations = planFontRegistrations(
    fontManifest,
    textFonts: textFonts,
    iconFonts: iconFonts,
    rootPackage: rootPackageName(),
  );

  final loadedFamilies = await loadFontRegistrations(
    registrations,
    register: (family, assets) async {
      final fontLoader = FontLoader(family);
      for (final asset in assets) {
        fontLoader.addFont(loadFontAsset(asset, load: rootBundle.load));
      }
      await fontLoader.load();
    },
  );

  // Load Roboto from Flutter SDK if not already loaded from the manifest
  if (textFonts && !loadedFamilies.contains('Roboto')) {
    final loaded = await _loadRobotoFromSdk();
    if (!loaded) {
      debugPrint(
        'golden_matrix: Roboto not found in FontManifest.json or Flutter SDK. '
        'Material text will render with the Ahem placeholder font (square boxes). '
        'Set FLUTTER_ROOT or add Roboto to your pubspec.yaml fonts.',
      );
    }
  }

  // Load MaterialIcons from Flutter SDK if not already loaded from the manifest.
  // Closes the gap for projects without a `cupertino_icons` dependency, where
  // icons would otherwise render as empty boxes.
  if (iconFonts && !loadedFamilies.contains('MaterialIcons')) {
    await _loadMaterialIconsFromSdk();
  }
}

/// Loads one font asset's bytes, retrying with a percent-**decoded** key when
/// the key from `FontManifest.json` fails to resolve.
///
/// Variable fonts are conventionally named with square brackets
/// (`Geist[wght].ttf`, `Inter[opsz,wght].ttf`). `[` and `]` are URI gen-delims,
/// so `flutter_tools` writes the manifest entry — and, under `flutter test`, the
/// file in `build/unit_test_assets/` — percent-encoded (`Geist%5Bwght%5D.ttf`).
/// `PlatformAssetBundle.load` then encodes the key *again*, looks for
/// `Geist%255Bwght%255D.ttf` and misses. Feeding it the decoded key
/// (`Geist[wght].ttf`) makes its single encoding land on the real filename.
///
/// The raw key is always tried first, so nothing changes for the normal case
/// and for platforms where the encoded key is the one that resolves.
@visibleForTesting
Future<ByteData> loadFontAsset(
  String asset, {
  required Future<ByteData> Function(String key) load,
}) async {
  try {
    return await load(asset);
  } on Object {
    final decoded = _percentDecodedOrNull(asset);
    // Nothing to decode, or the key is not valid percent-encoding (a literal
    // '%' in the filename) — surface the original asset failure.
    if (decoded == null || decoded == asset) rethrow;
    return load(decoded);
  }
}

/// [Uri.decodeFull] for [key], or `null` when it is not valid percent-encoding.
///
/// Catches broadly on purpose: the SDK signals invalid encoding with
/// `ArgumentError('Invalid URL encoding')`, older/other versions with a
/// `FormatException`, and this helper performs no other operation that could
/// fail — a decoding hiccup must never mask the asset error it came from.
String? _percentDecodedOrNull(String key) {
  try {
    return Uri.decodeFull(key);
  } on Object {
    return null;
  }
}

/// Performs the registrations planned by [planFontRegistrations], isolating
/// failures: a family that cannot be loaded is reported through [onWarning]
/// (`debugPrint` by default) and skipped, instead of aborting the whole run.
///
/// This matters because [loadAppFonts] is awaited in `flutter_test_config.dart`
/// — a throw there fails the **entire test file at load time**, before any test
/// runs. A single unloadable font asset in a transitive dependency would take
/// down every golden in the file, including the ones that never use that font.
///
/// Returns the families that actually loaded. Only successful registrations are
/// included, so a failed `Roboto`/`MaterialIcons` entry in the manifest does not
/// suppress the Flutter SDK fallbacks in [loadAppFonts].
///
/// Registrations sharing the same asset list (a family and its
/// [namespacedAlias]) warn only once — one broken file, one message.
@visibleForTesting
Future<Set<String>> loadFontRegistrations(
  Iterable<({String family, List<String> assets})> registrations, {
  required Future<void> Function(String family, List<String> assets) register,
  void Function(String message)? onWarning,
}) async {
  final loadedFamilies = <String>{};
  final warnedAssets = <String>{};

  for (final reg in registrations) {
    try {
      await register(reg.family, reg.assets);
      loadedFamilies.add(reg.family);
    } on Object catch (error) {
      if (warnedAssets.add(reg.assets.join(','))) {
        (onWarning ?? debugPrint)(
          'golden_matrix: skipped font family "${reg.family}" '
          '(${reg.assets.join(", ")}): $error. Goldens that use it fall back to '
          'another font. Asset names containing "[" or "]" (the variable-font '
          'convention) cannot be loaded through AssetBundle — see '
          'https://mavoryl.github.io/golden_matrix/font-namespacing/',
        );
      }
    }
  }

  return loadedFamilies;
}

/// Pure planning step for [loadAppFonts]: turns the raw `FontManifest.json`
/// entries into the list of `(family, assets)` registrations to perform,
/// applying the [textFonts]/[iconFonts] filter, de-duplicating family names,
/// and appending the `packages/<root>/<family>` self-test alias (see
/// [namespacedAlias]) for bare text families.
@visibleForTesting
List<({String family, List<String> assets})> planFontRegistrations(
  Object? fontManifest, {
  required bool textFonts,
  required bool iconFonts,
  String? rootPackage,
}) {
  final out = <({String family, List<String> assets})>[];
  final seen = <String>{};

  // `FontManifest.json` is generated by the Flutter tool, but a tool version
  // that changes its shape must not be able to abort `flutter_test_config.dart`
  // and take every test in the file with it — the same reason
  // [loadFontRegistrations] isolates the registrations themselves.
  if (fontManifest is! Iterable) {
    warnGoldenMatrix(
      'FontManifest.json is a ${fontManifest.runtimeType}, not a list of font '
      'families; no fonts were registered from it. Text will render with the '
      'Ahem placeholder font.',
    );
    return out;
  }

  for (final dynamic font in fontManifest) {
    final String family;
    final List<String> assets;
    try {
      final fontMap = font as Map<String, dynamic>;
      family = derivedFontFamily(fontMap);
      assets = <String>[
        for (final dynamic fontType in (fontMap['fonts'] as Iterable<dynamic>? ?? const []))
          if ((fontType as Map<String, dynamic>)['asset'] is String) fontType['asset'] as String,
      ];
    } catch (e) {
      warnGoldenMatrix('skipping an unreadable FontManifest.json entry ($font): $e');
      continue;
    }

    if (family.isEmpty) continue;
    final isIcon = isIconFamily(family);
    if (isIcon && !iconFonts) continue;
    if (!isIcon && !textFonts) continue;

    if (seen.add(family)) out.add((family: family, assets: assets));

    final alias = namespacedAlias(family, rootPackage, isIcon: isIcon);
    if (alias != null && seen.add(alias)) out.add((family: alias, assets: assets));
  }

  return out;
}

/// Reads the root package name from a `pubspec.yaml` (the project under test,
/// `pubspec.yaml` in the current working directory by default).
///
/// Returns `null` when the file is missing or has no parseable `name:` key —
/// in which case [loadAppFonts] simply skips the namespaced-alias step.
@visibleForTesting
String? rootPackageName({String pubspecPath = 'pubspec.yaml'}) {
  final file = File(pubspecPath);
  if (!file.existsSync()) return null;
  for (final line in file.readAsLinesSync()) {
    final match = RegExp(r'''^name:\s*['"]?([A-Za-z_][A-Za-z0-9_]*)''').firstMatch(line);
    if (match != null) return match.group(1);
  }
  return null;
}

/// The `packages/<root>/<family>` name a bare text [family] should *also* be
/// registered under so that a package referencing its own fonts with that
/// prefix resolves when it tests itself. Returns `null` when no alias applies:
/// icon families, already-prefixed families, overridable system fonts, an
/// empty family, or a missing [rootPackage].
@visibleForTesting
String? namespacedAlias(String family, String? rootPackage, {required bool isIcon}) {
  if (isIcon) return null;
  if (rootPackage == null || rootPackage.isEmpty) return null;
  if (family.isEmpty || family.startsWith('packages/')) return null;
  if (_overridableFonts.contains(family)) return null;
  return 'packages/$rootPackage/$family';
}

/// Heuristic check for whether [family] looks like an icon font family.
///
/// Returns `true` when the family name (case-insensitive) contains
/// `'icons'` or `'symbols'`. Catches `MaterialIcons`, `CupertinoIcons`,
/// `FontAwesomeIcons`, `MaterialSymbolsRounded`, etc.
///
/// Misses icon fonts that don't follow this convention (e.g. `Phosphor`).
/// Exposed for testing and for users who want to mirror the same filter
/// in their own code.
@visibleForTesting
bool isIconFamily(String family) {
  final lower = family.toLowerCase();
  return lower.contains('icons') || lower.contains('symbols');
}

/// Attempts to load the Roboto font from the Flutter SDK's cached artifacts.
/// Returns `true` if the font was loaded, `false` otherwise.
Future<bool> _loadRobotoFromSdk() async {
  final flutterRoot = _findFlutterRoot();
  if (flutterRoot == null) return false;

  final robotoFile = File(joinPath(_materialFontsDir(flutterRoot), 'Roboto-Regular.ttf'));

  if (!robotoFile.existsSync()) return false;

  final fontLoader = FontLoader('Roboto');
  final bytes = await robotoFile.readAsBytes();
  fontLoader.addFont(Future.value(ByteData.view(bytes.buffer)));
  await fontLoader.load();
  return true;
}

/// Attempts to load the MaterialIcons font from the Flutter SDK's cached
/// artifacts. Returns `true` if the font was loaded, `false` otherwise.
///
/// This complements the `FontManifest.json` path: projects with a
/// `cupertino_icons` (or any package that re-exports MaterialIcons)
/// dependency get the font from the manifest; everyone else used to
/// see empty boxes. With this fallback, icon glyphs render in goldens
/// regardless of project configuration.
Future<bool> _loadMaterialIconsFromSdk() async {
  final flutterRoot = _findFlutterRoot();
  if (flutterRoot == null) return false;

  final iconsFile = File(joinPath(_materialFontsDir(flutterRoot), 'MaterialIcons-Regular.otf'));

  if (!iconsFile.existsSync()) return false;

  final fontLoader = FontLoader('MaterialIcons');
  final bytes = await iconsFile.readAsBytes();
  fontLoader.addFont(Future.value(ByteData.view(bytes.buffer)));
  await fontLoader.load();
  return true;
}

/// `<root>/bin/cache/artifacts/material_fonts`, joined for this platform.
String _materialFontsDir(String flutterRoot) => ['bin', 'cache', 'artifacts', 'material_fonts']
    .fold(flutterRoot, (path, segment) => joinPath(path, segment));

/// Splits a `PATH`-style value into directories.
///
/// Empty entries are dropped: on POSIX an empty `PATH` entry means the current
/// directory, and probing that for a Flutter SDK is noise.
@visibleForTesting
List<String> splitSearchPath(String? path, {String? separator}) {
  if (path == null || path.isEmpty) return const [];
  final sep = separator ?? (Platform.isWindows ? ';' : ':');
  return path.split(sep).where((entry) => entry.isNotEmpty).toList();
}

/// The file names the Flutter launcher can have on this platform.
///
/// The lookup used to be `Process.runSync('which', ['flutter'])`, which is not
/// a command on Windows — and even if it were, the launcher there is
/// `flutter.bat`, not an extension-less binary.
@visibleForTesting
List<String> flutterExecutableNames({bool? windows}) =>
    (windows ?? Platform.isWindows) ? const ['flutter.bat', 'flutter.exe'] : const ['flutter'];

/// The SDK root containing [executablePath], which is expected to look like
/// `<root>/bin/flutter`. Returns `null` when it does not.
///
/// The old derivation was `resolved.split('/bin/flutter').first`, a literal
/// POSIX path with the POSIX launcher name baked in. On Windows it never
/// matched, so the whole path was returned as the "root" and every SDK font
/// lookup beneath it missed — silently, because a missing font falls back to
/// Ahem.
@visibleForTesting
String? flutterRootFromExecutable(String executablePath, {String? separator}) {
  final sep = separator ?? Platform.pathSeparator;
  final parts = executablePath.split(sep);
  if (parts.length < 3) return null;
  if (parts[parts.length - 2] != 'bin') return null;
  return parts.sublist(0, parts.length - 2).join(sep);
}

/// Finds the Flutter SDK root by checking common indicators.
String? _findFlutterRoot() {
  // Check FLUTTER_ROOT environment variable
  final envRoot = Platform.environment['FLUTTER_ROOT'];
  if (envRoot != null && Directory(envRoot).existsSync()) {
    return envRoot;
  }

  // Walk PATH ourselves rather than shelling out: no `which`/`where` split by
  // platform, no subprocess, and the launcher's name comes from
  // [flutterExecutableNames].
  for (final dir in splitSearchPath(Platform.environment['PATH'])) {
    for (final name in flutterExecutableNames()) {
      final candidate = File(joinPath(dir, name));
      if (!candidate.existsSync()) continue;
      try {
        final root = flutterRootFromExecutable(candidate.resolveSymbolicLinksSync());
        if (root != null && Directory(joinPath(joinPath(root, 'bin'), 'cache')).existsSync()) {
          return root;
        }
      } catch (_) {
        // A broken symlink or a permission error here just means this PATH
        // entry is not the SDK; keep looking.
      }
    }
  }

  return null;
}

/// Resolves the correct font family name, handling package namespacing.
///
/// Fonts from packages are prefixed with `packages/<package_name>/` in
/// the asset path. This function detects that and applies the correct
/// qualified name so Flutter can match the font at runtime.
@visibleForTesting
String derivedFontFamily(Map<String, dynamic> fontDefinition) {
  if (!fontDefinition.containsKey('family')) {
    return '';
  }

  final fontFamily = fontDefinition['family'] as String;

  if (_overridableFonts.contains(fontFamily)) {
    return fontFamily;
  }

  if (fontFamily.startsWith('packages/')) {
    final fontFamilyName = fontFamily.split('/').last;
    if (_overridableFonts.any((font) => font == fontFamilyName)) {
      return fontFamilyName;
    }
  } else {
    final fonts = fontDefinition['fonts'] as Iterable<dynamic>;
    for (final dynamic fontType in fonts) {
      final fontTypeMap = fontType as Map<String, dynamic>;
      final asset = fontTypeMap['asset'] as String?;
      if (asset != null && asset.startsWith('packages')) {
        final packageName = asset.split('/')[1];
        return 'packages/$packageName/$fontFamily';
      }
    }
  }

  return fontFamily;
}
