import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

/// Well-known system fonts that should not be namespaced with a package prefix.
const _overridableFonts = [
  'Roboto',
  '.SF UI Display',
  '.SF UI Text',
  '.SF Pro Text',
  '.SF Pro Display',
];

/// Loads fonts declared in the app's pubspec.yaml and its dependencies.
///
/// Two sources are consulted, in order:
///
/// 1. **`FontManifest.json`** — the manifest generated by the Flutter
///    tool, listing every font family bundled by the app and its
///    dependencies. Each eligible family in the manifest is registered
///    with Flutter's [FontLoader].
/// 2. **Roboto + MaterialIcons from the Flutter SDK cache** — if either
///    is not already present in the manifest, this function locates the
///    SDK (via `FLUTTER_ROOT` or by resolving `which flutter`) and loads
///    `bin/cache/artifacts/material_fonts/Roboto-Regular.ttf` /
///    `MaterialIcons-Regular.otf`. These fallbacks let Material widgets
///    render real glyphs in tests instead of the default Ahem placeholder
///    text and empty-box icons.
///
/// Call this in `flutter_test_config.dart` before running golden tests:
///
/// ```dart
/// // test/flutter_test_config.dart
/// Future<void> testExecutable(FutureOr<void> Function() testMain) async {
///   await loadAppFonts();
///   return testMain();
/// }
/// ```
///
/// ## Selective loading
///
/// Pass [textFonts] and/or [iconFonts] to load only a subset:
///
/// ```dart
/// // Layout-deterministic tests — Ahem text geometry + real icons.
/// // Useful when text metrics drift across macOS/Linux CI but icons
/// // must still be visually recognizable for review.
/// await loadAppFonts(textFonts: false);
///
/// // Real text, no icons — niche, but supported.
/// await loadAppFonts(iconFonts: false);
///
/// // Pure Ahem — equivalent to never calling loadAppFonts().
/// await loadAppFonts(textFonts: false, iconFonts: false);
/// ```
///
/// Icon families are detected by the [isIconFamily] heuristic
/// (case-insensitive substring match on `'icons'` or `'symbols'`).
/// This catches `MaterialIcons`, `CupertinoIcons`, `FontAwesomeIcons`,
/// `MaterialSymbolsRounded`, etc. Icon fonts that don't follow this
/// naming convention (e.g. `Phosphor`) will be treated as text fonts
/// — file an issue if this matters for your project.
Future<void> loadAppFonts({bool textFonts = true, bool iconFonts = true}) async {
  TestWidgetsFlutterBinding.ensureInitialized();

  // Load fonts from FontManifest.json (app + dependency fonts)
  final fontManifest = await rootBundle.loadStructuredData<Iterable<dynamic>>(
    'FontManifest.json',
    (string) async => json.decode(string) as Iterable<dynamic>,
  );

  final loadedFamilies = <String>{};

  for (final dynamic font in fontManifest) {
    final fontMap = font as Map<String, dynamic>;
    final family = derivedFontFamily(fontMap);
    final isIcon = isIconFamily(family);
    if (isIcon && !iconFonts) continue;
    if (!isIcon && !textFonts) continue;

    loadedFamilies.add(family);
    final fontLoader = FontLoader(family);
    for (final dynamic fontType in fontMap['fonts'] as Iterable<dynamic>) {
      final fontTypeMap = fontType as Map<String, dynamic>;
      fontLoader.addFont(rootBundle.load(fontTypeMap['asset'] as String));
    }
    await fontLoader.load();
  }

  // Load Roboto from Flutter SDK if not already loaded from the manifest
  if (textFonts && !loadedFamilies.contains('Roboto')) {
    final loaded = await _loadRobotoFromSdk();
    if (!loaded) {
      debugPrint(
        'golden_matrix: Roboto not found in FontManifest.json or Flutter SDK. '
        'Material text will render with the Ahem placeholder font (square boxes). '
        'Set FLUTTER_ROOT or add Roboto to your pubspec.yaml fonts.',
      );
    }
  }

  // Load MaterialIcons from Flutter SDK if not already loaded from the manifest.
  // Closes the gap for projects without a `cupertino_icons` dependency, where
  // icons would otherwise render as empty boxes.
  if (iconFonts && !loadedFamilies.contains('MaterialIcons')) {
    await _loadMaterialIconsFromSdk();
  }
}

/// Heuristic check for whether [family] looks like an icon font family.
///
/// Returns `true` when the family name (case-insensitive) contains
/// `'icons'` or `'symbols'`. Catches `MaterialIcons`, `CupertinoIcons`,
/// `FontAwesomeIcons`, `MaterialSymbolsRounded`, etc.
///
/// Misses icon fonts that don't follow this convention (e.g. `Phosphor`).
/// Exposed for testing and for users who want to mirror the same filter
/// in their own code.
@visibleForTesting
bool isIconFamily(String family) {
  final lower = family.toLowerCase();
  return lower.contains('icons') || lower.contains('symbols');
}

/// Attempts to load the Roboto font from the Flutter SDK's cached artifacts.
/// Returns `true` if the font was loaded, `false` otherwise.
Future<bool> _loadRobotoFromSdk() async {
  final flutterRoot = _findFlutterRoot();
  if (flutterRoot == null) return false;

  final robotoFile = File('$flutterRoot/bin/cache/artifacts/material_fonts/Roboto-Regular.ttf');

  if (!robotoFile.existsSync()) return false;

  final fontLoader = FontLoader('Roboto');
  final bytes = await robotoFile.readAsBytes();
  fontLoader.addFont(Future.value(ByteData.view(bytes.buffer)));
  await fontLoader.load();
  return true;
}

/// Attempts to load the MaterialIcons font from the Flutter SDK's cached
/// artifacts. Returns `true` if the font was loaded, `false` otherwise.
///
/// This complements the `FontManifest.json` path: projects with a
/// `cupertino_icons` (or any package that re-exports MaterialIcons)
/// dependency get the font from the manifest; everyone else used to
/// see empty boxes. With this fallback, icon glyphs render in goldens
/// regardless of project configuration.
Future<bool> _loadMaterialIconsFromSdk() async {
  final flutterRoot = _findFlutterRoot();
  if (flutterRoot == null) return false;

  final iconsFile = File(
    '$flutterRoot/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf',
  );

  if (!iconsFile.existsSync()) return false;

  final fontLoader = FontLoader('MaterialIcons');
  final bytes = await iconsFile.readAsBytes();
  fontLoader.addFont(Future.value(ByteData.view(bytes.buffer)));
  await fontLoader.load();
  return true;
}

/// Finds the Flutter SDK root by checking common indicators.
String? _findFlutterRoot() {
  // Check FLUTTER_ROOT environment variable
  final envRoot = Platform.environment['FLUTTER_ROOT'];
  if (envRoot != null && Directory(envRoot).existsSync()) {
    return envRoot;
  }

  // Find flutter in PATH and resolve symlinks
  final result = Process.runSync('which', ['flutter']);
  if (result.exitCode == 0) {
    final flutterBin = (result.stdout as String).trim();
    try {
      final resolved = File(flutterBin).resolveSymbolicLinksSync();
      // resolved is something like /path/to/flutter/bin/flutter
      final root = resolved.split('/bin/flutter').first;
      if (Directory('$root/bin/cache').existsSync()) {
        return root;
      }
    } catch (_) {
      // Ignore resolution errors
    }
  }

  return null;
}

/// Resolves the correct font family name, handling package namespacing.
///
/// Fonts from packages are prefixed with `packages/<package_name>/` in
/// the asset path. This function detects that and applies the correct
/// qualified name so Flutter can match the font at runtime.
@visibleForTesting
String derivedFontFamily(Map<String, dynamic> fontDefinition) {
  if (!fontDefinition.containsKey('family')) {
    return '';
  }

  final fontFamily = fontDefinition['family'] as String;

  if (_overridableFonts.contains(fontFamily)) {
    return fontFamily;
  }

  if (fontFamily.startsWith('packages/')) {
    final fontFamilyName = fontFamily.split('/').last;
    if (_overridableFonts.any((font) => font == fontFamilyName)) {
      return fontFamilyName;
    }
  } else {
    final fonts = fontDefinition['fonts'] as Iterable<dynamic>;
    for (final dynamic fontType in fonts) {
      final fontTypeMap = fontType as Map<String, dynamic>;
      final asset = fontTypeMap['asset'] as String?;
      if (asset != null && asset.startsWith('packages')) {
        final packageName = asset.split('/')[1];
        return 'packages/$packageName/$fontFamily';
      }
    }
  }

  return fontFamily;
}
